version: '3.8'
services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./docker-client/Dockerfile.client
  cypress:
    container_name: cypress
    depends_on:
      - client
    build:
      context: ./
      dockerfile: Dockerfile.cypress
    environment:
      - "CYPRESS_BASE_URL=http://client/"